### ISSUE TITLE
No contact form

### ISSUE THREAD

**Issue by AlecsisDuarte** [luisduenas/brainstorm-site#1]
I noticed that there is a [Contact](https://github.com/luisduenas/brainstorm-site/blob/413545d2a7050a3f258e4beda0f62b9c57ddb7df/src/components/header.js#L31-L34) button on the header, but I don't see any way to contact the owner/company of this web page.

This button only takes you to the bottom/footer of the page

**Comment by luisduenas** [comment]
i like it that way

**Comment by AlecsisDuarte** [comment]
Then I guess I will close this issue 😢
