### ISSUE TITLE
Our Skills icons not centered

### ISSUE THREAD

**Issue by AlecsisDuarte** [luisduenas/brainstorm-site#2]
In my laptop screen the [3 icons ](https://github.com/luisduenas/brainstorm-site/blob/master/src/pages/index.js#L247-L263) used to represent the skills are not centered or at least not in my screen - 13 inch display (1680x1050)

![Screenshot of the skills section](https://user-images.githubusercontent.com/18224162/70205495-0cff6580-16d9-11ea-9180-4edd6862e2bb.png)

**Comment by luisduenas** [comment]
Currently the containters of the images are centred but the content inside them not (see image below).
That's a very easy fix, would you like to work on it?
![image](https://user-images.githubusercontent.com/16164843/70247916-07346f00-172f-11ea-8505-12585b356d97.png)

**Comment by AlecsisDuarte** [comment]
Yeah, I'll work on it
